# Generated by Django 5.2.3 on 2025-07-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
